### ISSUE TITLE
render crashes when playing a video

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/scratch-render#12]
when playing a video with the video extension, the renderer crashes. audio still plays
this happens when using the [video extension](https://extensions.turbowarp.org/Lily/Video.js) from the extension gallery 
here is how to recreate the error, and what the console outputs:

https://github.com/user-attachments/assets/373fce9d-e0b4-4661-9430-3711ad1bc23a

![image](https://github.com/user-attachments/assets/5c891f79-24ff-49b3-879a-8caf10713468)

tested on  chromium 126 linux

**Comment by TheShovel** [comment]
![image](https://github.com/user-attachments/assets/3db323fc-7af9-4c06-a843-6faf09fe895a)
this specific line of code in skins.js seems to be the issue

**Comment by GarboMuffin** [comment]
chrome bug :/

**Comment by TheShovel** [comment]
man this sucks. I guess ill have to add some kind of failsafe for the people that get this. Ill close the issue whenever chrome fixes this :(

**Comment by GarboMuffin** [comment]
might work now

it is a chrome bug, given that it used to work fine in chrome and still works in firefox. but can still seemingly be worked around

**Comment by TheShovel** [comment]
> might work now
> 
> it is a chrome bug, given that it used to work fine in chrome and still works in firefox. but can still seemingly be worked around

thank you!
