### ISSUE TITLE
WebGPU support

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/scratch-render#4]
Using the new WebGPU API could really speed up certain projects.
This is just a suggestion, but it should be considered.
Maybe even make it an experimental option in the packager to report bugs and so on if you decide to do this.

**Comment by TheShovel** [comment]
Someone already made an implementation of this, but it would be nice to see it with all the TurboWarp stuff.
https://github.com/jamesbmadden/scratch-render-webgpu

**Comment by raymonable** [comment]
WebGPU would only speed up rendering. Lots of slow projects are slow because they're still doing major computation on the CPU.
